varnish-rs/varnish-rs

examples/vmod_vdp/src/lib.rs
examples/vmod_vfp/src/lib.rs
src/vcl/processor.rs

This resolves issue #15
It changes the mutability of Ctx in the new method in both the VDP/VFP interfaces to allow modifications of things such as headers.

Ctx should be mutable in the new method of VDPs and VFPs

---

src/vcl/backend.rs
src/vcl/convert.rs
src/vcl/ctx.rs
src/vmodtool-rs.py

See https://rust-lang.github.io/rust-clippy/master/index.html#/manual_c_str_literals

use c-consts `c"..."` instead of the `b"...\\0"`

---

Cargo.toml
examples/vmod_be/src/lib.rs
examples/vmod_error/src/lib.rs
examples/vmod_event/src/lib.rs
examples/vmod_example/src/lib.rs
examples/vmod_object/src/lib.rs
examples/vmod_vdp/src/lib.rs
examples/vmod_vfp/src/lib.rs
src/lib.rs
src/vcl/backend.rs
src/vcl/convert.rs
src/vcl/ctx.rs
src/vcl/http.rs
src/vcl/probe.rs
src/vcl/processor.rs
src/vcl/ws.rs
src/vsc.rs
varnish-sys/src/lib.rs
vmod_test/src/lib.rs

* reformat with `cargo +nightly fmt --all -- --config imports_granularity=Module,group_imports=StdExternalCrate`
* add clippy lint configuration to Cargo.toml
This seems like a bug, but I didn't change the logic:
```rust
self.raw.protover = match value {
"HTTP/0.9" => 9,
// FIXME: Is this a bug?
"HTTP/1.0" | "HTTP/1.1" => 10,
"HTTP/2.0" => 20,
_ => 0,
};
```

A few small lints

---

.github/workflows/tests.yaml
Cargo.toml
README.md
src/vmodtool-rs.py

P.S. Note that CI currently fails - not certain why yet
I copied some of these from many of my crates like https://github.com/nyurik/sqlite-hashes (eventually I think it is better to use `just` to simplify the process, and make it identical for the developer and CI)
* removed the `no-libvarnish` job -- not used
* remove rust installation - it is always pre-installed unless you want an older version, e.g. for msrv test
* use build cache
* add all sorts of tests
* no need to do a loop over vmod - enough to just say `cargo ... --workspace`
* not much value in `RUST_BACKTRACE=1` I think - if it fails, longer backtrace won't tell you much in CI
* add doc testing

Improve github action workflow

---

.github/workflows/tests.yaml
Cargo.toml
build.rs
examples/vmod_be/Cargo.toml
examples/vmod_error/Cargo.toml
examples/vmod_error/src/lib.rs
examples/vmod_event/Cargo.toml
examples/vmod_event/src/lib.rs
examples/vmod_example/Cargo.toml
examples/vmod_example/src/lib.rs
examples/vmod_infiniteloop/Cargo.toml
examples/vmod_infiniteloop/src/lib.rs
examples/vmod_object/Cargo.toml
examples/vmod_timestamp/Cargo.toml
examples/vmod_vdp/Cargo.toml
examples/vmod_vdp/src/lib.rs
examples/vmod_vfp/Cargo.toml
examples/vmod_vfp/src/lib.rs
src/lib.rs
src/vcl/ctx.rs
src/vcl/ws.rs
vmod_test/Cargo.toml
vmod_test/src/lib.rs

Make all crates use the same linting rules, and fixed a few.
Note that I fixed `extra_unused_lifetimes` for `unsafe extern "C" fn chunk_collector(...)` -- which looked a bit suspicious, but seems to be ok.  Need CI tests! :)

More linting

---

examples/vmod_vdp/src/lib.rs
examples/vmod_vfp/src/lib.rs
src/vcl/processor.rs
vmod_test/src/lib.rs

Make ordering of the trait impl the same as in definition, and modify return to prevent accidental mismatches.

Fix trait order and type

---

src/error.rs
src/lib.rs
src/vsc.rs

There does not seem to be any reason to keep `Error` and `Result` in both `vcl` and `vsc` modules.
Also, note that `vcl::Error` is actually never instantiated.
In the future, I think it would be better to rename them, e.g. to `VarnishError` and `VarnishResult`.  This is a common practice now to distinguish them from the built-in ones (lots of people have been complaining that `std::io::Result` and others didn't follow that convention, but it is too late for that now).

Consolidate `Error` and `Result`

---

CHANGELOG.md
src/lib.rs

This ensures varnishtest will fail much quicker by default.

Set `VARNISHTEST_DURATION=5s` by default

---

examples/vmod_example/src/lib.rs
src/lib.rs
src/vcl/vpriv.rs

* Use dedicated `tests` module (recommended practice)
* Use `#[cfg(test)]` on both test module and `vtc!` macro to speed up compilation for non-test cases (and avoids including junk in the output)
| Use "hide whitespace" when reviewing |
|---|
| ![image](https://github.com/user-attachments/assets/db61ac20-4b87-4114-a9b8-d116db54b786) |

Clean up tests

---

examples/vmod_vfp/src/lib.rs
src/vcl/backend.rs
src/vcl/convert.rs
src/vcl/http.rs
src/vcl/processor.rs
src/vcl/ws.rs

* remove NULL-char related comments when using `CStr` - that's the definition of it.
* casting `cstr.as_ptr()` with `.cast::<c_char>()` is redundant - it's already that.
* modify `WS::copy_bytes_with_null` to return `CStr`, and marked it as `unsafe`. Current implementation relies on the input value to not contain any `\0` chars, and would result in UB otherwise.
See also #46

Some CStr cleanup

---

src/vcl/backend.rs
src/vcl/ctx.rs
src/vcl/http.rs
src/vcl/processor.rs
src/vcl/vpriv.rs
src/vcl/vsb.rs
src/vcl/ws.rs

Makes debugging far easier. Includes a few tiny lints.

Add `Debug` trait to all structs and enums

---

.github/workflows/tests.yaml
Cargo.toml
src/vcl/probe.rs
vmod_test/Cargo.toml

* Now `serde` requires `serde` feature to be manually enabled
* Add build/testing of both "default" and "all features" modes
* Refactored Cargo.toml a bit -- now some shared values are in one place, moved all lints to the bottom (as least important)
* Removed some Cargo.toml values because their values are the same as used by default (per doc, only recommended when different)

Make Serde into an optional dependency

---

src/vcl/backend.rs
src/vcl/ctx.rs
src/vcl/http.rs
src/vcl/utils.rs

Add a few helper methods to help with converting txt to str and back, which also helps with the header parsing.  As a tiny addition, also simplified `TestCtx` instantiation.

Make `ffi::Txt` safer and simpler to use

---

build.rs
src/bindings.rs.saved
src/vcl/convert.rs

Introduce a wrapper for `VCL_BOOL` type, per #51

Wrap `VCL_BOOL` in a struct to ensure type safety

---

build.rs
src/bindings.rs.saved
src/vcl/convert.rs
src/vmodtool-rs.py

This removes the deref (not needed). I tried to add `VCL_BYTES`, but hit a snag (into_result() conflicts because of multiple i64->Result). I might have to finish the proc macro before doing the rest of them.

Wrap `VCL_INT` and `VCL_REAL`

---

src/vcl/convert.rs
src/vcl/vpriv.rs

* Make `Vpriv` store a reference instead of a pointer, with an attached lifetime.  Unfortunately we have to support `into_rust` which must fake it with `'static`.
* Do not double-wrap name string - first as a `CString` inside a `Box` because `CString` is already heap-allocated.
* Improve `store` fn

Minor `VPriv` improvements

---

examples/vmod_event/src/lib.rs
src/vcl/backend.rs
src/vcl/ctx.rs
src/vmodtool-rs.py

This replaces #68 without the extra struct

Optimize log usage - take 2

---

CHANGELOG.md
src/lib.rs

`vtc!` macro now supported debug mode, e.g. `vtc!(file, true)` - keeps the temporary files and always prints the output.

Add debug mode to the `vtc!` macro

---

src/vcl/backend.rs
src/vcl/ctx.rs
src/vcl/ws.rs
src/vmodtool-rs.py

* Add `try_into` to parse `ffi::vcl_event_e` value without panicking
* In backend `wrap_event` callback, panic with a better message including the backend type (is this ok?)
* move all remaining tests to the separate `#[cfg(test)]` mods

`Event` cleanup

---

examples/vmod_vdp/src/lib.rs
examples/vmod_vfp/src/lib.rs
src/vcl/processor.rs
vmod_test/src/lib.rs

There is no reason to have a crashing code, when we can have compiler refuse to compile.
Also do a few tiny styling cleanups. Static `name` should probably be first, and `Sized` can use shorter notation

Remove `unimplementd!` from the `VFP` trait

---

varnish-sys/build.rs

This fixes an issue with varnishapi lib not being installed - the `link-lib` command should only be done after we know it exists

Minor ordering in the build script

---

examples/vmod_error/src/lib.rs
varnish-sys/src/vcl/ctx.rs
vmod_test/src/lib.rs

it seems `fail() -> u8` was a hack to benefit the `vmod_error` example.  `fail()` should not have any results.
Also, a minor unrelated fix - inlined format args in the test.

fail() should not return anything

---

.cargo/config.toml
.github/workflows/tests.yaml
varnish-sys/src/vcl/convert.rs

* It is better to allow warnings to stay as warnings while development, but fail warnings in CI
* Also, discovered a bug that I flagged without fixing, just so it won't be forgotten

Remove warning as error flags for dev

---

CHANGELOG.md
Cargo.toml
examples/vmod_be/src/lib.rs
examples/vmod_error/src/lib.rs
examples/vmod_event/src/lib.rs
examples/vmod_example/src/lib.rs
examples/vmod_infiniteloop/src/lib.rs
examples/vmod_object/src/lib.rs
examples/vmod_timestamp/src/lib.rs
examples/vmod_vdp/src/lib.rs
examples/vmod_vfp/src/lib.rs
varnish/Cargo.toml
varnish/src/lib.rs
varnish/src/varnishtest.rs
vmod_test/src/lib.rs

Use proper strings and full paths to run unit tests. Ensures that all test files are executed, rather than forcing devs to remember to add a new .vtc file to the list. Fill fail if no files are found. Also allows users to do their own testing using function calls.
```rust
varnish::run_vtc_tests!("tests/*.vtc");
```

Improve tests, adding glob support

---

.github/workflows/tests.yaml
examples/vmod_vdp/src/lib.rs
justfile
varnish-sys/Cargo.toml
varnish-sys/build.rs
varnish-sys/src/bindings.rs.saved
varnish-sys/src/vcl/processor.rs
varnish/Cargo.toml

Detect which varnish is installed, and generate appropriate code.
Adds CI tests for `7.[456]` versions
Note that this also updates the saved bindings to 7.6 - used only when generating docs.

Support varnish 7.4, 7.5, and 7.6 in one package

---

varnish-sys/bindings.for-docs
varnish-sys/build.rs

* Update `bindings.for-docs` to the latest
* Verify the generated file matches - and if not, print a warning with a helpful cp command.  This won't show if  the warning is generated while using this crate from crates.io

Compare validate and saved file, warn if differ

---

.github/workflows/tests.yaml
CHANGELOG.md
Cargo.toml
README.md
varnish-sys/src/vcl/convert.rs
varnish/src/lib.rs

* Add lots of documentation on how to use the new macro-based approach
* This ensures the main branch is always conforming with the semver rules - if the API is breaking, it must increment minor (for 0.*.*), and major (for 1+.*.*).  See https://github.com/obi1kenobi/cargo-semver-checks

Document macro-based approach, bump to v0.1.0

---

CHANGELOG.md
examples/vmod_vdp/src/lib.rs
examples/vmod_vfp/src/lib.rs
varnish-macros/snapshots/function_types@code.snap
varnish-macros/src/model.rs
varnish-macros/src/parser_args.rs
varnish-macros/tests/pass/function.rs
varnish-sys/src/vcl/backend.rs
varnish-sys/src/vcl/convert.rs
varnish-sys/src/vcl/ctx.rs
varnish-sys/src/vcl/error.rs
varnish-sys/src/vcl/http.rs
varnish-sys/src/vcl/probe.rs
varnish-sys/src/vcl/processor.rs
varnish-sys/src/vcl/vsb.rs
varnish-sys/src/vcl/ws.rs
varnish/src/vsc.rs
vmod_test/src/lib.rs

* `COWProbe` struct to `CowProbe`
* `COWRequest` struct to `CowRequest`
* `HTTP` struct to `HttpHeaders`
* `HTTPIter` struct to `HttpHeadersIter`
* `VDPCtx` struct to `DeliveryProcCtx`
* `VDP` trait to `DeliveryProcessor`
* `VFPCtx` struct to `FetchProcCtx`
* `VFP` trait to `FetchProcessor`
* `VSB` struct to `Buffer`
* `VSB::cat` function to `Buffer::write`

Name cleanups

---

Cargo.toml
examples/vmod_object/src/lib.rs
varnish-macros/src/gen_docs.rs
varnish-macros/src/gen_func.rs
varnish-macros/src/model.rs
varnish-macros/src/names.rs
varnish-macros/src/parser.rs
varnish-macros/src/parser_utils.rs
varnish-sys/src/extensions.rs
varnish-sys/src/vcl/backend.rs
varnish-sys/src/vcl/convert.rs
varnish-sys/src/vcl/http.rs
varnish-sys/src/vcl/processor.rs
varnish-sys/src/vcl/vsb.rs
varnish-sys/src/vcl/ws.rs
varnish/src/vsc.rs
vmod_test/src/lib.rs

Many fixes were suggested by clippy (some are no longer listed in the Cargo.toml).  Other than cosmetic changes, did a few minor improvements:
* Add `Clone, Copy` traits to `StreamClose` enum
* `HttpHeaders` now has `iter()` method used by `IntoIterator` implementation. I also removed the IntoIterator on `&mut` - it does not seem to be needed.
* I am still really worried about `transmute::<u32, VslTag>((self.raw.logtag as u32) + u32::from(HDR_FIRST))` -- seems like a major hack, but need feedback if this logic was correct.
* The `ws.alloc` API returns a pointer to the u8, which could be mis-aligned for bigger objects, and is currently marked as "safe". Need to rethink it.
* The `Buffer::write` returns `Result<(), ()>` -- we should return proper error - any thoughts?
* Should `Transfer` …

Some tiny clippy lint fixes

---

examples/vmod_object/Cargo.toml
examples/vmod_object/README.md
examples/vmod_object/src/lib.rs

A few followups to this:
* `pub struct` should NOT be allowed inside the vmod - it should be defined outside of it. Not sure why it is currently allowed.
* We may need to rethink `Send`/`Sync` requirements for objects.  Technically, the ownership of the object is sent to Varnish ... which I guess is like another thread - so must be `Send`?

Use much faster DashMap with vmod_kv example

---

varnish-macros/snapshots/docs_types@code.snap
varnish-macros/snapshots/event1_event@code.snap
varnish-macros/snapshots/event2_event2@code.snap
varnish-macros/snapshots/function_types@code.snap
varnish-macros/snapshots/object_obj@code.snap
varnish-macros/snapshots/object_obj@docs.snap
varnish-macros/snapshots/object_obj@json.snap
varnish-macros/snapshots/object_obj@model.snap
varnish-macros/snapshots/shared2_tuple@code.snap
varnish-macros/snapshots/shared3_tuple@code.snap
varnish-macros/snapshots/shared_task@code.snap
varnish-macros/snapshots/vcl_returns_vcl_returns@code.snap
varnish-macros/src/gen_func.rs
varnish-macros/src/generator.rs
varnish-macros/src/model.rs
varnish-macros/src/parser_args.rs
varnish-macros/tests/fail/error_obj.stderr
varnish-macros/tests/pass/object.rs
varnish-sys/src/vcl/convert.rs
varnish-sys/src/vcl/error.rs

Big rework of the wrapper function generation and error handling in the macros:
* input values like `VCL_STRING` can now fail properly when converting to `&str` or `Option<&str>` - i.e. if they are not proper UTF8.
* on failure, the user function is not called, and the call is considered as failed
* if the user wants to get "raw" input value, they have to use `Option<&CStr>`, or at least `&CStr` to treat `NULL` and `""` are the same thing.
* after calling the user function, its output conversion with `into_vcl()` can also fail - treat that as a failure of the function execution
* remove `Cow<'a, str>` internal usage - we no longer need it because we never use "lossy conversion" - a string either fails conversion - in which case user function is not called, or everything works as a …

Rework error handling with TryFrom

---

Cargo.toml
varnish-sys/Cargo.toml
varnish-sys/src/vcl/backend.rs
varnish-sys/src/vcl/ctx.rs
varnish-sys/src/vcl/error.rs

Convert it to an enum, implementing automatic `Display` and `From` support using `thiserror`. With enum, we no longer need to allocate a string in some cases in order to send it to the logging.

Speed up `VclError`

---

CHANGELOG.md
examples/vmod_infiniteloop/Cargo.toml
examples/vmod_object/src/lib.rs
examples/vmod_vfp/Cargo.toml
justfile
varnish-macros/Cargo.toml
varnish-macros/src/generator.rs
varnish/Cargo.toml
varnish/src/lib.rs
varnish/src/vsc.rs
vmod_test/Cargo.toml

This PR introduces `ffi` and `vsc` features, highlighting what API we treat as the more stable one.

Hide most FFI behind a feature flag

---

CHANGELOG.md
varnish-sys/src/vcl/convert.rs
varnish-sys/src/vcl/probe.rs
vmod_test/src/lib.rs

Keeping it much simpler - the only real difference between them is `String` vs `Cow<str>` for two fields.  A simple generic fixes that.

Make Probe and CowProbe into one struct

---

varnish-sys/src/vcl/processor.rs
varnish-sys/src/vcl/vsb.rs
varnish-sys/src/vcl/ws.rs

* constructors for wrapper types make no sense to be exposed. we can always re-enable them later if someone comes up with a reasonable usecase.
* a few minor inlining

hide constructors, minor nits

---

CHANGELOG.md
varnish-sys/src/vcl/backend.rs
varnish-sys/src/vcl/ctx.rs
varnish-sys/src/vcl/http.rs
varnish-sys/src/vcl/processor.rs
varnish-sys/src/vcl/vsb.rs
varnish-sys/src/vcl/ws.rs

For consistency with other structs like `Ctx`, whenever we create a wrapper for a C pointer, we should use the same function - `from_ptr`:  `Buffer`, `Workspace`, `HttpHeaders`, and `FetchProcCtx`

Rename `new` to `from_ptr` for several structs

---

varnish-macros/src/gen_func.rs
varnish/snapshots/docs_types@code.snap
varnish/snapshots/event1_event@code.snap
varnish/snapshots/function_types@code.snap
varnish/snapshots/object_obj@code.snap
varnish/snapshots/shared1_task@code.snap
varnish/snapshots/shared2_tuple@code.snap
varnish/snapshots/vcl_returns_vcl_returns@code.snap

A minor optimization - in a macro-generated function, check if the Rust context wrapper `Ctx` is needed, and if not, skip its creation.

Skip creating `__ctx` when not needed

---

CONTRIBUTING.md
docker/.gitignore
docker/Dockerfile
docker/startup.sh
justfile

Docker allows multiple Varnish versions on the same machine.  To use it, run `just docker-run-76` or any other version (run `just` to see a list).  On the first run, it will build the image, install needed dependencies, and then it will start the container.  The container will have the git root directory mounted as `/app`, so you can run `cargo build` and `cargo test` as usual. All work is preserved in the `docker/.cache/<version>`, so restarting container would not need re-install everything.
This will allow simpler #141 implementation

add multi-version docker support

---

Cargo.toml
docker/startup.sh
varnish-sys/Cargo.toml
varnish-sys/build.rs
varnish-sys/src/vcl/processor.rs

* Use `links` manifest key (see [docs](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key)) - this exports all metadata fields to all dependants.
With this change, any crate that depends on `varnish-sys` will have `DEP_VARNISHAPI_VERSION_NUMBER=6.0.13` env var set during the build, accessible from that crate's `build.rs`.  We can re-parse it, or better yet - add some more metadata values relevant to specific usecases.
* Do not declare hidden features in `Cargo.toml` - turns out there is a [special command](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-check-cfg) for that.
* Added a few tools to the docker

Easier build config reuse

---

.github/workflows/tests.yaml
docker/Dockerfile
justfile
varnish-macros/src/generator.rs
varnish-sys/src/extensions.rs
varnish/snapshots/docs_types@code.snap
varnish/snapshots/event1_event@code.snap
varnish/snapshots/event2_event2@code.snap
varnish/snapshots/event3_event3@code.snap
varnish/snapshots/event4_event4@code.snap
varnish/snapshots/function_types@code.snap
varnish/snapshots/object2_obj2@code.snap
varnish/snapshots/object_obj@code.snap
varnish/snapshots/shared1_task@code.snap
varnish/snapshots/shared2_tuple@code.snap
varnish/snapshots/shared3_tuple@code.snap
varnish/snapshots/vcl_returns_vcl_returns@code.snap
varnish/src/lib.rs

Get rid of the duplicate generated `VmodData`, move a few minor things from LTS 6.0 PR
Also, hides documentation of the ffi re-export structs as this is a "hidden" macro-support

Use `vmod_data`, varnishapi installation

---

CHANGELOG.md
Cargo.toml
examples/vmod_be/src/lib.rs
justfile
varnish-macros/src/errors.rs
varnish-macros/src/parser.rs
varnish-sys/src/vcl/backend.rs
varnish/snapshots/function_types@code.snap
varnish/snapshots/vcl_returns_vcl_returns@code.snap
varnish/snapshots_v6/function_types@code.snap
varnish/snapshots_v6/vcl_returns_vcl_returns@code.snap
varnish/tests/fail/error_fn.rs
varnish/tests/fail/error_fn.stderr
varnish/tests/fail/error_fn_args_dups.rs
varnish/tests/fail/error_fn_args_dups.stderr
varnish/tests/fail/error_fn_args_logic.rs
varnish/tests/fail/error_fn_args_logic.stderr
varnish/tests/fail/error_obj.stderr
varnish/tests/fail/error_obj_no_ctor.stderr
varnish/tests/pass/function.rs
varnish/tests/pass_ffi/vcl_returns.rs
varnish/tests/vmod_test/src/lib.rs

* Require all user functions that return `VCL_*` types to be `unsafe`
* updated changelog
* bump to v0.3.0
* do not report an error that no functions found if other errors were found too
Fixes #151

unsafe `VCL_*` returning functions, v0.3.0

---

.github/workflows/tests.yaml

`github actions` moved to `ubuntu:noble` and `varnish:7.4` isn't packaged for it, on top of being EOL

no more 7.4 in CI

---

CHANGELOG.md
justfile
varnish-sys/src/vcl/mod.rs
varnish-sys/src/vcl/ws.rs
varnish-sys/src/vcl/ws_str_buffer.rs
varnish/tests/pass/shared3.rs
varnish/tests/pass_ffi/vcl_returns.rs
varnish/tests/vmod_test/src/lib.rs

- Introduce `Workspace::get_str_buffer() -> WsStrBuffer` instead of `reserve`
- There is no longer any need to write NUL bytes to the end of the buffer
- The new buffer implements the `Write` trait, and can be inspected for what has been written so far
- The buffer does not allow any access to "dirty" (unset) portion of the buffer
- The buffer must be finalized with `finish() -> VCL_STRING`

rework Workspace and Buffer APIs

---

varnish-macros/src/parser.rs
varnish-sys/src/vcl/backend.rs

I modified the logic of the `wrap_finish` a bit - now it will properly handle if `htc` is null already, and won't crash.

Fix Clippy 1.85 lints + minor fix

---

CHANGELOG.md
justfile
varnish/Cargo.toml
varnish/src/lib.rs
varnish/src/metrics_reader.rs

A bunch of VSC-related renames per our chat. This way we won't conflict between metrics reader and metrics provider
* Fixed FFI memory bug - `patience` was passing "off" without the null termination to C
* Modified `patience`, refactoring it and making it return `Self` rather than `Result<Self>` 
* deleted `vsc` feature
* `mod vsc` -> inlined at the top crate level
* `Stats` -> `MetricsReader`
* `StatsImpl` -> `MetricsReaderImpl` (private)
* `StatsBuilder` -> `MetricsReaderBuilder`
* `Stat` -> `Metric`
* `Format` -> `MetricsFormat`
* Removed `Format::Unknown` value. This is a very `C-like` pattern that's almost non-existent in Rust. Converted `From` to `TryFrom` -- as it now can return an error  - using `()` for now.

`vsc` module cleanup

---

CHANGELOG.md
examples/vmod_be/README.md
examples/vmod_be/src/lib.rs
varnish-sys/src/utils.rs
varnish-sys/src/vcl/backend.rs

rename `Serve` &rarr; `vcl::VclBackend`, `Transfer` &rarr; `vcl::VclResponse`
This is just the first part of making it more readable. Any other naming suggestions?

Backend renames

---

justfile

The build may update README files, and we may forget to commit it

Ensure git is clean after the build

---

CHANGELOG.md
varnish-sys/src/txt.rs
varnish-sys/src/vcl/ctx.rs
varnish-sys/src/vcl/http.rs
varnish-sys/src/vcl/mod.rs
varnish-sys/src/vcl/str_or_bytes.rs
varnish/tests/vmod_test/README.md
varnish/tests/vmod_test/src/lib.rs
varnish/tests/vmod_test/tests/test01.vtc

This is based on @gquintard 's work in #182 - but introduces a new `StrOrBytes` header value.
Note that the current code still appends `NUL` after the header if it does not contain it.

Handle raw byte headers

---

Cargo.toml
justfile

* Updated version in the package configuration.
* Updated version in workspace dependencies.
* Removed outdated publishing step instructions from comments.

Bump version, remove unused publishing steps

---

varnish-sys/bindings.for-docs
varnish-sys/build.rs
varnish-sys/c_code/wrapper.h

Consolidate all varnish logic in a `VarnishInfo` struct.  This is part of the new vsc code, but cleanly separated to simplify review.

Refactor Varnish bindings generation

---

README.md
logo.svg

The logo is based on varnish-cache + the commonly-used rust gear... plus a few SVG hacks and fixes.
We may want to spend a bit more time with it and make it more like https://github.com/maplibre/maplibre-rs#readme
See also https://github.com/rust-lang/rust-artwork/blob/master/logo/rust-logo-gear-only.svg

Hack together a logo

---

CHANGELOG.md
Cargo.toml

* `varnish-sys`: 0.5.2 -> 0.5.3 (✓ API compatible changes)
* `varnish-macros`: 0.5.2 -> 0.5.3
* `varnish`: 0.5.2 -> 0.5.3 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- fix URLs to point to correct github org ([#216](https://github.com/varnish-rs/varnish-rs/pull/216))
</blockquote>
<blockquote>
- fix URLs to point to correct github org ([#216](https://github.com/varnish-rs/varnish-rs/pull/216))
</blockquote>
<blockquote>
- fix URLs to point to correct github org ([#216](https://github.com/varnish-rs/varnish-rs/pull/216))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).

chore: release v0.5.3

---

CHANGELOG.md
Cargo.toml

* `varnish-sys`: 0.5.3 -> 0.5.4 (✓ API compatible changes)
* `varnish-macros`: 0.5.3 -> 0.5.4
* `varnish`: 0.5.3 -> 0.5.4
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- test release process
</blockquote>
<blockquote>
- test release process
</blockquote>
<blockquote>
- test release process
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).

chore: release v0.5.4
