varnish-rs/varnish-rs

src/vcl/processor.rs, vmod_test/src/lib.rs, vmod_test/tests/test07.vtc, vmod_test/vmod.vcc
=> add null check to wrap_vfp_fini

src/vmodtool-rs.py
=> fix: import sys module

src/vcl/backend.rs, src/vcl/convert.rs, src/vcl/ctx.rs, src/vcl/http.rs, src/vcl/processor.rs, src/vcl/vpriv.rs, src/vcl/vsb.rs, src/vcl/ws.rs, src/vsc.rs
See https://rust-lang.github.io/rust-clippy/master/index.html#/ptr_as_ptr
=> use safer pointer casts

src/error.rs, src/lib.rs, src/vcl/backend.rs, src/vcl/convert.rs, src/vcl/ctx.rs, src/vcl/http.rs, src/vcl/probe.rs, src/vcl/processor.rs, src/vcl/vpriv.rs, src/vcl/vsb.rs, src/vcl/ws.rs, src/vmodtool-rs.py, src/vsc.rs
* Simplified `HTTP::new`
* Please check `header_from_hd` -- it seems `unwrap()` is not needed?
* `std::ffi` should be used instead of `std::os::raw` per [docs](https://doc.rust-lang.org/std/os/raw/)
* a few minor fixes like use statements, asserts, and doc links
=> more lints

src/lib.rs, src/vcl/backend.rs, src/vcl/processor.rs, src/vcl/utils.rs, src/vcl/ws.rs
This includes changes from #56, unifying magic number checks.
=> Refactor refs (review after 56)

src/vcl/backend.rs, src/vcl/convert.rs, src/vcl/ws.rs
* Move `WS_Allocated` into `WS`
* More refactorings
=> Move allocated check

src/vcl/backend.rs, src/vcl/utils.rs
One of my main goals of several recent refactorings is to get rid of as many `*(*(*foo).bar).baz` as possible, replacing them with proper `.as_ref().unwrap()` -- in other words replacing pointer dereferences with proper references. This ensures a single NULL validation location in the `.unwrap()`, and allows Rust to validate all references thereafter.  All these PRs should be considered as intermediary steps - I'm sure we can come up with a better overall abstraction that ensures that no `unsafe` API is exposed by default.
* consolidate `get_backend` into a single validatable function
* a few more wrapper validation functions for clearer intent
* Added a few more `FIXME` -- these are more like notes for future refactorings, to make sure we don't forget about them. Some of them could be …
=> Backend cleanups

src/vcl/backend.rs
Keeping things as refs is sooo much nicer...
=> Cleanup refs in vcl/backend.rs

src/vcl/ctx.rs
* Use standard `From` trait (which is actually only used internally.
* Add Clone & Copy trait
A bit of bike-shedding:
* TBD: usually these things are called `level`, or `log level` - a bit confusing about the tag, but no biggie.
* `Any` is kinda weird tbh, maybe call it `Other(u32)` ?
=> Minor improvement for `LogTag`

.github/workflows/tests.yaml, README.md, justfile
This allows to use the same commands during development and in CI
=> Add justfile and use it in workflows

varnish-macros/src/gen_func.rs
Just a minor cleanup with identical macro output as before - consolidates the steps used in the wrapper to do before and after calling user function
=> Cleanup macro pre-steps

CHANGELOG.md, examples/vmod_vdp/README.md, examples/vmod_vdp/src/lib.rs, examples/vmod_vfp/README.md, examples/vmod_vfp/src/lib.rs, varnish-sys/src/vcl/processor.rs, vmod_test/src/lib.rs
Do a few more renames to keep things easier for new users - even I had to lookup these names despite working with Varnish for a while to understand what they do.
=> Some more naming cleanup

varnish/src/varnishtest.rs, vmod_test/tests/test_skip.vtc
=> Implement varnishtest skipping

Cargo.toml, varnish-sys/Cargo.toml, varnish-sys/build.rs
The renamer is much better tested, and has more options to customize type generation.
=> Use my new bindgen_helpers crate

varnish-sys/bindings.for-docs, varnish-sys/build.rs
Use 7.6.1 output for doc build.
=> Update generated bindgen file to 7.6.1

varnish-sys/build.rs
Now reports the version of the found Varnish if it doesn't match the expected output.
=> Better build script output

.github/workflows/tests.yaml, Cargo.toml, justfile, varnish-sys/src/vcl/backend.rs, varnish-sys/src/vcl/ctx.rs, varnish-sys/src/vcl/ws.rs
This also discovered that some of our doc tests were not passing. Fixed.
=> doc test fixes, re-enable CI publish dry-run test

varnish-sys/src/lib.rs, varnish-sys/src/vcl/convert.rs, varnish-sys/src/vcl/http.rs, varnish-sys/src/vcl/probe.rs, varnish-sys/src/vcl/processor.rs, varnish-sys/src/vcl/vsb.rs, varnish-sys/src/vcl/ws.rs
=> Update to 1.83 clippies

varnish-macros/src/generator.rs, varnish/snapshots/docs_types@code.snap, varnish/snapshots/event1_event@code.snap, varnish/snapshots/event2_event2@code.snap, varnish/snapshots/event3_event3@code.snap, varnish/snapshots/event4_event4@code.snap, varnish/snapshots/function_types@code.snap, varnish/snapshots/object2_obj2@code.snap, varnish/snapshots/object_obj@code.snap, varnish/snapshots/shared1_task@code.snap, varnish/snapshots/shared2_tuple@code.snap, varnish/snapshots/shared3_tuple@code.snap, varnish/snapshots/vcl_returns_vcl_returns@code.snap, varnish/snapshots_v6/docs_types@code.snap, varnish/snapshots_v6/event1_event@code.snap, varnish/snapshots_v6/event2_event2@code.snap, varnish/snapshots_v6/event3_event3@code.snap, varnish/snapshots_v6/event4_event4@code.snap, varnish/snapshots_v6/function_types@code.snap, varnish/snapshots_v6/object2_obj2@code.snap, varnish/snapshots_v6/object_obj@code.snap, varnish/snapshots_v6/shared1_task@code.snap, varnish/snapshots_v6/shared2_tuple@code.snap, varnish/snapshots_v6/shared3_tuple@code.snap, varnish/snapshots_v6/vcl_returns_vcl_returns@code.snap
See also https://stackoverflow.com/questions/51481551/what-does-automatically-derived-mean
=> add `#[automatically_derived]` to generated code

varnish-macros/src/generator.rs, varnish/snapshots/docs_types@code.snap, varnish/snapshots/event1_event@code.snap, varnish/snapshots/event2_event2@code.snap, varnish/snapshots/event3_event3@code.snap, varnish/snapshots/event4_event4@code.snap, varnish/snapshots/function_types@code.snap, varnish/snapshots/object2_obj2@code.snap, varnish/snapshots/object_obj@code.snap, varnish/snapshots/shared1_task@code.snap, varnish/snapshots/shared2_tuple@code.snap, varnish/snapshots/shared3_tuple@code.snap, varnish/snapshots/vcl_returns_vcl_returns@code.snap, varnish/snapshots_v6/docs_types@code.snap, varnish/snapshots_v6/event1_event@code.snap, varnish/snapshots_v6/event2_event2@code.snap, varnish/snapshots_v6/event3_event3@code.snap, varnish/snapshots_v6/event4_event4@code.snap, varnish/snapshots_v6/function_types@code.snap, varnish/snapshots_v6/object2_obj2@code.snap, varnish/snapshots_v6/object_obj@code.snap, varnish/snapshots_v6/shared1_task@code.snap, varnish/snapshots_v6/shared2_tuple@code.snap, varnish/snapshots_v6/shared3_tuple@code.snap, varnish/snapshots_v6/vcl_returns_vcl_returns@code.snap
default is irrelevant for vmod
=> Ignore another clippy warning in user macro

CHANGELOG.md, varnish-sys/src/vcl/convert.rs, varnish/tests/vmod_test/README.md, varnish/tests/vmod_test/src/lib.rs, varnish/tests/vmod_test/tests/test08.vtc
=> fix overeager WS caching

.github/dependabot.yml, .github/workflows/dependabot.yml
Ensure github automatically suggests dependency updates, and applies them automatically if all the tests pass.  I copy/pasted this from all my other projects
=> Automate dependabot PRs

.dockerignore, .github/workflows/tests.yaml, docker/Dockerfile, docker/startup.sh, justfile
Consolidates installation of Varnish in Docker and CI, making it also part of the release step.
=> Consolidate varnish installation

.github/workflows/tests.yaml, Cargo.toml, docker/Dockerfile
=> Minor dependency updates and cleanups

justfile
I wrote a small util to sort all my justfiles,
and used it here to keep things a bit more organized.
https://gist.github.com/nyurik/8a6db6bfcd0eb7de52287071e63c8ac5
=> Sort justfiles alphabetically

README.md, justfile
Getting ready to publish a patch via automated release process to retest CI
=> chore: minor readme and regex updates

.pre-commit-config.yaml, examples/vmod_be/tests/test01.vtc, examples/vmod_counters/tests/test01.vtc, examples/vmod_error/tests/test01.60.vtc, examples/vmod_error/tests/test01.vtc, examples/vmod_event/tests/test01.vtc, examples/vmod_example/tests/test01.vtc, examples/vmod_infiniteloop/tests/test01.vtc, examples/vmod_object/tests/test01.vtc, examples/vmod_timestamp/tests/test01.vtc, examples/vmod_vdp/tests/test01.vtc, examples/vmod_vfp/tests/test01.vtc, varnish-sys/build.rs, varnish-sys/c_code/wrapper.c, varnish/tests/vmod_test/tests/test01.vtc, varnish/tests/vmod_test/tests/test02.vtc, varnish/tests/vmod_test/tests/test03.vtc, varnish/tests/vmod_test/tests/test04.vtc, varnish/tests/vmod_test/tests/test05.vtc, varnish/tests/vmod_test/tests/test06.vtc, varnish/tests/vmod_test/tests/test07.vtc, varnish/tests/vmod_test/tests/test08.vtc
=> feat: forbid and autofix tab characters

CHANGELOG.md, Cargo.toml, examples/README.md, varnish-sys/src/vcl/backend.rs, varnish-sys/src/vcl/http.rs, varnish/src/lib.rs
=> chore: fix URLs to point to correct github org
